import { TestBed, ComponentFixture } from '@angular/core/testing';
import { SimpleChange } from '@angular/core';
import { CreateExpenseModalComponent } from './create-expense-modal.component';
import { ExpensesService } from '../../services/expenses.service';
import { FriendsService } from '../../../../features/friends/services/friends.service';
import { of, throwError } from 'rxjs';
import { HttpClientTestingModule } from '@angular/common/http/testing';
import { CATEGORY_OPTIONS } from '../../../../core/constants/app.constants';
import { GroupKeyService } from '../../../../core/services/group-key.service';
import { Store } from '@ngxs/store';
import { ClientEncryptionService } from '../../../../core/services/encryption.service';
import { CryptoSessionManager } from '../../../../core/services/crypto-session-manager.service';

/**
 * runWithRecovery's catch does an authoritative ensureCryptoContext() check
 * that is itself several microtask ticks deep — flush generously rather than
 * guessing the exact count (see crypto-recovery-queue.service.spec.ts).
 */
async function flushMicrotasks(times = 15): Promise<void> {
  for (let i = 0; i < times; i++) {
    await Promise.resolve();
  }
}

describe('CreateExpenseModalComponent', () => {
  let component: CreateExpenseModalComponent;
  let fixture: ComponentFixture<CreateExpenseModalComponent>;
  let mockExpensesService: any;
  let mockFriendsService: any;
  let mockGroupKeyService: any;
  let mockStore: any;
  let mockEncryptionService: any;

  beforeEach(async () => {
    // Mock localStorage for JWT token
    const mockToken =
      'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.' +
      btoa(JSON.stringify({ userId: 'user-1', email: 'test@example.com' })) +
      '.signature';
    jest.spyOn(Storage.prototype, 'getItem').mockImplementation((key) => {
      if (key === 'finmate_token') return mockToken;
      return null;
    });

    mockExpensesService = {
      createExpense: jest.fn().mockReturnValue(of({ id: 'exp-new' })),
      updateExpense: jest.fn().mockReturnValue(of({ id: 'exp-1' })),
      checkDuplicates: jest.fn().mockReturnValue(of([])),
    };

    mockFriendsService = {
      searchUsers: jest.fn().mockReturnValue(of([])),
    };

    const mockCryptoKey = {} as CryptoKey;
    mockGroupKeyService = {
      getGroupDataKey: jest.fn().mockResolvedValue(mockCryptoKey),
      createGroupKey: jest.fn().mockResolvedValue(mockCryptoKey),
      resolveGroupKey: jest
        .fn()
        .mockResolvedValue({ status: 'ready', key: mockCryptoKey }),
      createAndStoreGroupKey: jest.fn().mockResolvedValue(mockCryptoKey),
      rateLimitError: jest.fn().mockReturnValue(null),
    };

    mockStore = {
      // Selectors generated by @Selector() (e.g. AuthState.getUser) are called
      // with the feature substate directly, not the root store state — NGXS's
      // real Store.selectSnapshot does that slicing internally. CryptoSessionManager
      // now calls store.selectSnapshot(AuthState.getUser) via runWithRecovery's
      // ensureCryptoContext() check, so this mock must match that shape or every
      // ensureCryptoContext() call rejects as "No crypto session is available",
      // regardless of the email mocked below.
      selectSnapshot: jest
        .fn()
        .mockImplementation((selector: (state: any) => unknown) =>
          selector({
            token: mockToken,
            refreshToken: null,
            user: { email: 'test@example.com', userId: 'user-1' },
            persistenceWarning: null,
          }),
        ),
    };

    mockEncryptionService = {
      loadKeyFromSession: jest.fn().mockResolvedValue(mockCryptoKey),
      generateDataKey: jest.fn().mockResolvedValue(mockCryptoKey),
      encryptBytes: jest.fn().mockResolvedValue('encrypted-bytes'),
      encrypt: jest.fn().mockResolvedValue('encrypted-value'),
      wrapKey: jest.fn().mockResolvedValue('wrapped-key'),
    };

    await TestBed.configureTestingModule({
      imports: [CreateExpenseModalComponent, HttpClientTestingModule],
      providers: [
        { provide: ExpensesService, useValue: mockExpensesService },
        { provide: FriendsService, useValue: mockFriendsService },
        { provide: GroupKeyService, useValue: mockGroupKeyService },
        { provide: Store, useValue: mockStore },
        { provide: ClientEncryptionService, useValue: mockEncryptionService },
      ],
    }).compileComponents();

    fixture = TestBed.createComponent(CreateExpenseModalComponent);
    component = fixture.componentInstance;
  });

  afterEach(() => {
    jest.restoreAllMocks();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });

  // --- Form validation ---
  describe('form validation', () => {
    it('should have form invalid when empty', () => {
      expect(component.expenseForm.valid).toBeFalsy();
    });

    it('should require title', () => {
      const titleControl = component.expenseForm.get('title');
      expect(titleControl?.hasError('required')).toBeTruthy();
    });

    it('should enforce title maxLength of 160', () => {
      const titleControl = component.expenseForm.get('title');
      titleControl?.setValue('a'.repeat(161));
      expect(
        titleControl?.hasError('maxLength') ||
          titleControl?.hasError('maxlength'),
      ).toBeTruthy();
    });

    it('should require amountTotal', () => {
      const amountControl = component.expenseForm.get('amountTotal');
      expect(amountControl?.hasError('required')).toBeTruthy();
    });

    it('should enforce minimum amount of 0.01', () => {
      const amountControl = component.expenseForm.get('amountTotal');
      amountControl?.setValue(0);
      expect(amountControl?.hasError('min')).toBeTruthy();
    });

    it('should accept valid amount', () => {
      const amountControl = component.expenseForm.get('amountTotal');
      amountControl?.setValue(10.5);
      expect(amountControl?.hasError('min')).toBeFalsy();
    });

    it('should require currency', () => {
      const currencyControl = component.expenseForm.get('currency');
      expect(currencyControl?.hasError('required')).toBeTruthy();
    });

    it('should require paidByUserId', () => {
      const paidByControl = component.expenseForm.get('paidByUserId');
      expect(paidByControl?.hasError('required')).toBeTruthy();
    });

    it('should default expenseDate to today', () => {
      const dateControl = component.expenseForm.get('expenseDate');
      const today = component.getTodayDateString();
      expect(dateControl?.value).toBe(today);
    });

    it('should default category to first option', () => {
      const categoryControl = component.expenseForm.get('category');
      expect(categoryControl?.value).toBe(CATEGORY_OPTIONS[0].value);
    });
  });

  // --- ngOnChanges ---
  describe('ngOnChanges', () => {
    it('should patch form when expense input changes (edit mode)', () => {
      component.expense = {
        id: 'exp-1',
        title: 'Groceries',
        description: 'Weekly shop',
        amountTotal: 50,
        currency: 'USD',
        category: 'food',
        expenseDate: '2026-06-28',
        paidByUserId: 'user-1',
        ownerUserId: 'user-1',
        version: 1,
      } as any;

      component.ngOnChanges({
        expense: {
          currentValue: component.expense,
          previousValue: null,
          firstChange: true,
          isFirstChange: () => true,
        },
      });

      expect(component.expenseForm.get('title')?.value).toBe('Groceries');
      expect(component.expenseForm.get('amountTotal')?.value).toBe(50);
    });

    it('resolves group-member payer/splits to user ids in edit mode', () => {
      // Group expenses come back with paidByUserId/participantUserId = null and
      // the ids in paidByGroupMemberId/participantGroupMemberId; the payer
      // dropdown and participant checkboxes are keyed by user id, so these must
      // be resolved via `members` or "Paid By"/"Split Among" render empty.
      component.groupId = 'group-1';
      component.members = [
        {
          id: 'm1',
          joinStatus: 'active',
          role: 'owner',
          user: { id: 'u1', email: 'a@b.com' },
        },
        {
          id: 'm2',
          joinStatus: 'active',
          role: 'member',
          user: { id: 'u2', email: 'c@d.com' },
        },
      ] as any;
      component.expense = {
        id: 'exp-2',
        title: 'Rent',
        amountTotal: 1000,
        currency: 'INR',
        category: 'housing',
        expenseDate: '2026-07-01',
        paidByUserId: null,
        paidByGroupMemberId: 'm1',
        ownerUserId: 'u1',
        version: 1,
        splits: [
          { participantUserId: null, participantGroupMemberId: 'm1' },
          { participantUserId: null, participantGroupMemberId: 'm2' },
        ],
      } as any;

      component.ngOnChanges({
        expense: {
          currentValue: component.expense,
          previousValue: null,
          firstChange: true,
          isFirstChange: () => true,
        },
      });

      expect(component.expenseForm.get('paidByUserId')?.value).toBe('u1');
      expect(component.selectedUserIds.has('u1')).toBeTruthy();
      expect(component.selectedUserIds.has('u2')).toBeTruthy();
      // Not flagged as modified when nothing was actually changed.
      expect(component.hasChanges()).toBeFalsy();
    });

    it('should patch currency from group', () => {
      component.groupCurrency = 'EUR';
      component.ngOnChanges({
        groupCurrency: {
          currentValue: 'EUR',
          previousValue: 'USD',
          firstChange: false,
          isFirstChange: () => false,
        },
      });

      expect(component.expenseForm.get('currency')?.value).toBe('EUR');
    });

    it('should select all active non-spectator members as participants', () => {
      component.members = [
        {
          id: 'm1',
          joinStatus: 'active',
          role: 'owner',
          user: { id: 'u1', email: 'a@b.com' },
        },
        {
          id: 'm2',
          joinStatus: 'active',
          role: 'spectator',
          user: { id: 'u2', email: 'c@d.com' },
        },
        {
          id: 'm3',
          joinStatus: 'active',
          role: 'member',
          user: { id: 'u3', email: 'e@f.com' },
        },
      ] as any;
      component.groupId = 'group-1';

      component.ngOnChanges({
        members: {
          currentValue: component.members,
          previousValue: [],
          firstChange: true,
          isFirstChange: () => true,
        },
      });

      // Spectator should NOT be selected as a participant
      expect(component.selectedUserIds.has('u1')).toBeTruthy();
      expect(component.selectedUserIds.has('u2')).toBeFalsy();
      expect(component.selectedUserIds.has('u3')).toBeTruthy();
    });
  });

  // --- Edit-mode change detection ---
  describe('change detection (edit mode)', () => {
    const openInEditMode = (overrides: Record<string, unknown> = {}) => {
      component.groupId = 'group-1';
      component.members = [
        {
          id: 'm1',
          role: 'owner',
          user: { id: 'user-1', email: 'a@b.com', displayName: 'Alice' },
        },
        {
          id: 'm2',
          role: 'member',
          user: { id: 'user-2', email: 'c@d.com', displayName: 'Bob' },
        },
      ] as any;
      component.expense = {
        id: 'exp-1',
        title: 'Dinner',
        description: 'Taxi',
        amountTotal: 120,
        currency: 'USD',
        category: 'food',
        expenseDate: '2026-06-28',
        paidByUserId: 'user-1',
        ownerUserId: 'user-1',
        version: 3,
        splits: [
          { participantUserId: 'user-1', splitType: 'percent', shareValue: 60 },
          { participantUserId: 'user-2', splitType: 'percent', shareValue: 40 },
        ],
        ...overrides,
      } as any;

      component.ngOnChanges({
        expense: {
          currentValue: component.expense,
          previousValue: null,
          firstChange: true,
          isFirstChange: () => true,
        },
      });
    };

    it('reports no changes immediately after opening in edit mode', () => {
      openInEditMode();
      expect(component.hasChanges()).toBe(false);
      expect(component.changeSummary()).toEqual([]);
    });

    it('detects a changed field and marks it modified', () => {
      openInEditMode();
      component.expenseForm.patchValue({ amountTotal: 150 });

      expect(component.hasChanges()).toBe(true);
      expect(component.isFieldModified('amountTotal')).toBe(true);
      expect(component.isFieldModified('title')).toBe(false);

      const amountChange = component
        .changeSummary()
        .find((c) => c.key === 'amountTotal');
      expect(amountChange).toEqual({
        key: 'amountTotal',
        label: 'Amount',
        from: '$120.00',
        to: '$150.00',
      });
    });

    it('detects participant changes', () => {
      openInEditMode();
      component.toggleParticipant('user-2'); // remove Bob

      expect(component.isFieldModified('participants')).toBe(true);
    });

    it('does NOT call updateExpense when nothing changed (no-op guard)', async () => {
      openInEditMode();

      await component.onSubmit();

      expect(mockExpensesService.updateExpense).not.toHaveBeenCalled();
      expect(component.errorMessage).toBe('No changes detected.');
    });

    it('preserves the original split configuration when participants are unchanged', async () => {
      openInEditMode();
      component.expenseForm.patchValue({ title: 'Dinner (updated)' });

      await component.onSubmit();

      expect(mockExpensesService.updateExpense).toHaveBeenCalledWith(
        'exp-1',
        expect.objectContaining({
          splits: [
            {
              participantUserId: 'user-1',
              participantGroupMemberId: undefined,
              splitType: 'percent',
              shareValue: 60,
            },
            {
              participantUserId: 'user-2',
              participantGroupMemberId: undefined,
              splitType: 'percent',
              shareValue: 40,
            },
          ],
        }),
      );
    });

    it('falls back to an equal split when the participant set changes', async () => {
      openInEditMode();
      component.toggleParticipant('user-2'); // remove Bob → participants changed

      await component.onSubmit();

      const call = mockExpensesService.updateExpense.mock.calls[0][1];
      expect(call.splits).toEqual([
        { participantUserId: 'user-1', splitType: 'equal', shareValue: 1 },
      ]);
    });
  });

  // --- Participant management ---
  describe('participant toggling', () => {
    it('should add participant when toggled on', () => {
      component.toggleParticipant('user-2');
      expect(component.selectedUserIds.has('user-2')).toBeTruthy();
    });

    it('should remove participant when toggled off', () => {
      component.selectedUserIds.add('user-2');
      component.toggleParticipant('user-2');
      expect(component.selectedUserIds.has('user-2')).toBeFalsy();
    });
  });

  // --- File attachment ---
  describe('file attachments', () => {
    it('should add files on selection', () => {
      const readSpy = jest
        .spyOn(FileReader.prototype, 'readAsArrayBuffer')
        .mockImplementation(function (this: FileReader) {
          Object.defineProperty(this, 'result', {
            value: new ArrayBuffer(8),
            configurable: true,
          });
          this.onload?.(new ProgressEvent('load'));
        });

      const file = new File(['receipt'], 'receipt.jpg', {
        type: 'image/jpeg',
      });
      const mockEvent = {
        target: {
          files: [file],
        },
      } as any;

      component.onFileSelected(mockEvent);
      expect(component.attachedFiles).toHaveLength(1);
      expect(component.attachedFiles[0].name).toBe('receipt.jpg');
      readSpy.mockRestore();
    });

    it('should remove attachment by index', () => {
      component.attachedFiles = [
        { name: 'a.jpg', size: '1 KB', key: 'k1' },
        { name: 'b.jpg', size: '2 KB', key: 'k2' },
      ];

      component.removeAttachment(0);
      expect(component.attachedFiles).toHaveLength(1);
      expect(component.attachedFiles[0].name).toBe('b.jpg');
    });
  });

  // --- Submit ---
  describe('onSubmit', () => {
    beforeEach(() => {
      component.groupId = 'group-1';
      component.selectedUserIds.add('user-1');
      component.expenseForm.patchValue({
        title: 'Test Expense',
        amountTotal: 100,
        currency: 'USD',
        category: 'food',
        expenseDate: '2026-06-28',
        paidByUserId: 'user-1',
      });
    });

    it('should call createExpense when form is valid and no existing expense', async () => {
      await component.onSubmit();

      expect(mockExpensesService.createExpense).toHaveBeenCalledWith(
        expect.objectContaining({
          title: 'Test Expense',
          amountTotal: 100,
          currency: 'USD',
          groupId: 'group-1',
        }),
      );
    });

    it('should show the duplicate warning and not save when a matching transaction exists', async () => {
      mockExpensesService.checkDuplicates.mockReturnValue(
        of([
          {
            id: 'exp-existing',
            title: 'Dinner',
            amountTotal: 100,
            currency: 'USD',
            category: 'food',
            expenseDate: '2026-06-28',
            transactionType: 'expense',
            paidByUserId: 'user-1',
          },
        ]),
      );

      await component.onSubmit();

      expect(mockExpensesService.checkDuplicates).toHaveBeenCalledWith(
        expect.objectContaining({
          amountTotal: 100,
          expenseDate: '2026-06-28',
          currency: 'USD',
          transactionType: 'expense',
          groupId: 'group-1',
        }),
      );
      expect(component.showDuplicateDialog()).toBe(true);
      expect(component.potentialDuplicates().length).toBe(1);
      expect(mockExpensesService.createExpense).not.toHaveBeenCalled();
    });

    it('proceeds with the save when the user confirms "This is a New Transaction"', async () => {
      mockExpensesService.checkDuplicates.mockReturnValue(
        of([
          {
            id: 'exp-existing',
            title: 'Dinner',
            amountTotal: 100,
            currency: 'USD',
            category: 'food',
            expenseDate: '2026-06-28',
            transactionType: 'expense',
            paidByUserId: 'user-1',
          },
        ]),
      );

      await component.onSubmit();
      expect(component.showDuplicateDialog()).toBe(true);

      await component.confirmNewTransaction();

      expect(component.showDuplicateDialog()).toBe(false);
      expect(mockExpensesService.createExpense).toHaveBeenCalled();
      // The resubmit skips the check it already showed the user — it must
      // not re-run it a second time for the same confirmed submission.
      expect(mockExpensesService.checkDuplicates).toHaveBeenCalledTimes(1);
    });

    it('cancels the save and returns to the form when the user confirms "This is the Same Transaction"', async () => {
      mockExpensesService.checkDuplicates.mockReturnValue(
        of([
          {
            id: 'exp-existing',
            title: 'Dinner',
            amountTotal: 100,
            currency: 'USD',
            category: 'food',
            expenseDate: '2026-06-28',
            transactionType: 'expense',
            paidByUserId: 'user-1',
          },
        ]),
      );

      await component.onSubmit();
      expect(component.showDuplicateDialog()).toBe(true);

      component.confirmSameTransaction();

      expect(component.showDuplicateDialog()).toBe(false);
      expect(component.potentialDuplicates().length).toBe(0);
      expect(mockExpensesService.createExpense).not.toHaveBeenCalled();
    });

    it('should call updateExpense when editing an existing expense', async () => {
      component.expense = {
        id: 'exp-1',
        version: 2,
      } as any;

      await component.onSubmit();

      expect(mockExpensesService.updateExpense).toHaveBeenCalledWith(
        'exp-1',
        expect.objectContaining({
          title: 'Test Expense',
          version: 2,
        }),
      );
    });

    it('submits exact amount splits when they add up to the total', async () => {
      component.members = [
        {
          id: 'm1',
          joinStatus: 'active',
          role: 'owner',
          user: { id: 'user-1', email: 'a@b.com', displayName: 'Alice' },
        },
        {
          id: 'm2',
          joinStatus: 'active',
          role: 'member',
          user: { id: 'user-2', email: 'c@d.com', displayName: 'Bob' },
        },
      ] as any;
      component.selectedUserIds.add('user-2');
      component.selectSplitMode('fixed');
      component.setExactSplitAmount('user-1', 60);
      component.setExactSplitAmount('user-2', 40);

      await component.onSubmit();

      expect(mockExpensesService.createExpense).toHaveBeenCalledWith(
        expect.objectContaining({
          splits: [
            { participantUserId: 'user-1', splitType: 'fixed', shareValue: 60 },
            { participantUserId: 'user-2', splitType: 'fixed', shareValue: 40 },
          ],
        }),
      );
    });

    it('does not submit exact amount splits while money is unassigned', async () => {
      component.members = [
        {
          id: 'm1',
          joinStatus: 'active',
          role: 'owner',
          user: { id: 'user-1', email: 'a@b.com', displayName: 'Alice' },
        },
        {
          id: 'm2',
          joinStatus: 'active',
          role: 'member',
          user: { id: 'user-2', email: 'c@d.com', displayName: 'Bob' },
        },
      ] as any;
      component.selectedUserIds.add('user-2');
      component.selectSplitMode('fixed');
      component.setExactSplitAmount('user-1', 60);
      component.setExactSplitAmount('user-2', 20);

      await component.onSubmit();

      expect(component.errorMessage).toBe(
        'Split amounts must add up to the total.',
      );
      expect(mockExpensesService.createExpense).not.toHaveBeenCalled();
    });
    it('should not submit when form is invalid', async () => {
      component.expenseForm.patchValue({ title: '' });
      await component.onSubmit();

      expect(mockExpensesService.createExpense).not.toHaveBeenCalled();
      expect(mockExpensesService.updateExpense).not.toHaveBeenCalled();
    });

    it('should not submit when no participants are selected', async () => {
      component.selectedUserIds.clear();
      await component.onSubmit();

      expect(mockExpensesService.createExpense).not.toHaveBeenCalled();
    });

    it('should set user-friendly error message on failure', async () => {
      mockExpensesService.createExpense.mockReturnValue(
        throwError(() => ({ error: { message: 'Internal server error 500' } })),
      );

      await component.onSubmit();

      expect(component.errorMessage).toBeDefined();
      expect(component.isSubmitting).toBe(false);
    });

    it('queues the save instead of failing when the crypto session is genuinely not ready at the encrypt+POST step, then auto-resumes once unlocked', async () => {
      // ExpensesService.createExpense() does its own, separate
      // ensureCryptoContext() check inside encryptPayload() — independent of
      // resolveGroupScopeKey()'s own check above it. ExpensesService itself
      // is mocked in this file, so simulate that internal failure directly:
      // the first call fails the way encryptPayload() would when the master
      // key isn't loaded, the retry (after "unlock") succeeds.
      mockEncryptionService.loadKeyFromSession.mockResolvedValue(null);
      mockExpensesService.createExpense
        .mockReturnValueOnce(
          throwError(() => new Error('Secure session is not ready')),
        )
        .mockReturnValueOnce(of({ id: 'exp-new' }));

      const pending = component.onSubmit();
      await flushMicrotasks();

      // Still paused, not failed — no premature error to dismiss.
      expect(component.isSubmitting).toBe(true);
      expect(component.errorMessage).toBe('');

      mockEncryptionService.loadKeyFromSession.mockResolvedValue({} as any);
      const cryptoSession = TestBed.inject(CryptoSessionManager);
      await cryptoSession.ensureCryptoContext();
      await pending;

      expect(mockExpensesService.createExpense).toHaveBeenCalledTimes(2);
      expect(component.isSubmitting).toBe(false);
      expect(component.errorMessage).toBe('');
    });

    it('should emit expenseCreated and close modal on success', async () => {
      const closeSpy = jest.spyOn(component.closeModalEvent, 'emit');
      const createdSpy = jest.spyOn(component.expenseCreated, 'emit');

      await component.onSubmit();

      expect(createdSpy).toHaveBeenCalled();
      expect(closeSpy).toHaveBeenCalled();
    });
  });

  // --- Modal close ---
  describe('closeModal', () => {
    it('should emit closeModalEvent', () => {
      const spy = jest.spyOn(component.closeModalEvent, 'emit');
      component.closeModal();
      expect(spy).toHaveBeenCalled();
    });
  });

  // --- Friend search ---
  describe('friend search', () => {
    it('should search users when query is >= 2 characters', () => {
      jest.useFakeTimers();
      try {
        mockFriendsService.searchUsers.mockReturnValue(
          of([{ id: 'u2', displayName: 'Jane', email: 'jane@example.com' }]),
        );

        component.onSearchChange('ja');
        jest.advanceTimersByTime(250);

        expect(mockFriendsService.searchUsers).toHaveBeenCalledWith('ja');
      } finally {
        jest.useRealTimers();
      }
    });

    it('should not search when query is < 2 characters', () => {
      component.onSearchChange('j');

      expect(mockFriendsService.searchUsers).not.toHaveBeenCalled();
      expect(component.searchResults).toEqual([]);
    });

    it('should add friend to split and clear search', () => {
      const friend = {
        id: 'u2',
        displayName: 'Jane',
        email: 'jane@example.com',
      };

      component.addFriendToSplit(friend);

      expect(component.resolvedFriends.has('u2')).toBeTruthy();
      expect(component.selectedUserIds.has('u2')).toBeTruthy();
      expect(component.searchQuery).toBe('');
      expect(component.searchResults).toEqual([]);
    });

    it('should remove friend from split', () => {
      component.resolvedFriends.set('u2', {
        id: 'u2',
        displayName: 'Jane',
        email: '',
      });
      component.selectedUserIds.add('u2');

      component.removeFriendFromSplit('u2');

      expect(component.resolvedFriends.has('u2')).toBeFalsy();
      expect(component.selectedUserIds.has('u2')).toBeFalsy();
    });

    it('should not remove current user from split', () => {
      jest.spyOn(component, 'getCurrentUserId').mockReturnValue('user-1');
      component.selectedUserIds.add('user-1');

      component.removeFriendFromSplit('user-1');

      expect(component.selectedUserIds.has('user-1')).toBeTruthy();
    });
  });

  // --- Group key classification (pending / no_session) ---
  describe('group key resolution', () => {
    const mockCryptoKey = {} as CryptoKey;

    const validForm = () => {
      component.groupId = 'group-1';
      component.selectedUserIds.add('user-1');
      component.expenseForm.patchValue({
        title: 'Test Expense',
        amountTotal: 100,
        currency: 'USD',
        category: 'food',
        expenseDate: '2026-06-28',
        paidByUserId: 'user-1',
      });
    };

    const asOwner = () => {
      component.members = [{ user: { id: 'user-1' }, role: 'owner' } as any];
    };

    const asMember = () => {
      component.members = [{ user: { id: 'user-1' }, role: 'member' } as any];
    };

    it('ready: uses the resolved key without minting a new one', async () => {
      mockGroupKeyService.resolveGroupKey.mockResolvedValue({
        status: 'ready',
        key: mockCryptoKey,
      });
      validForm();

      await component.onSubmit();

      expect(mockGroupKeyService.createAndStoreGroupKey).not.toHaveBeenCalled();
      expect(mockExpensesService.createExpense).toHaveBeenCalled();
    });

    it('pending + owner/admin: mints the key inline and proceeds', async () => {
      mockGroupKeyService.resolveGroupKey.mockResolvedValue({
        status: 'pending',
      });
      mockGroupKeyService.createAndStoreGroupKey.mockResolvedValue(
        mockCryptoKey,
      );
      validForm();
      asOwner();

      await component.onSubmit();

      expect(mockGroupKeyService.createAndStoreGroupKey).toHaveBeenCalledWith(
        'group-1',
      );
      expect(component.scopeKeyStatus()).toBe('ready');
      expect(mockExpensesService.createExpense).toHaveBeenCalled();
    });

    it('pending + non-owner: does NOT mint and surfaces a friendly error', async () => {
      mockGroupKeyService.resolveGroupKey.mockResolvedValue({
        status: 'pending',
      });
      validForm();
      asMember();

      await component.onSubmit();

      expect(mockGroupKeyService.createAndStoreGroupKey).not.toHaveBeenCalled();
      expect(mockExpensesService.createExpense).not.toHaveBeenCalled();
      expect(component.errorMessage).toContain("group key hasn't been shared");
      expect(component.isSubmitting).toBe(false);
    });

    it('no_session: does NOT mint and reports a session-specific error', async () => {
      mockGroupKeyService.resolveGroupKey.mockResolvedValue({
        status: 'no_session',
      });
      validForm();
      asOwner();

      await component.onSubmit();

      expect(mockGroupKeyService.createAndStoreGroupKey).not.toHaveBeenCalled();
      expect(mockExpensesService.createExpense).not.toHaveBeenCalled();
      expect(component.errorMessage).toContain('session needs to be unlocked');
    });

    it('scopeKeyBlocked is true for no_session, but scopeKeyMessage is empty — the shared CryptoRecoveryPanel handles it instead of a local message', () => {
      component.groupId = 'group-1';
      component.scopeKeyStatus.set('no_session');

      expect(component.scopeKeyBlocked()).toBe(true);
      expect(component.scopeKeyMessage()).toBe('');
    });

    it('renders the shared <app-crypto-recovery-panel> in the template for no_session, not a local banner', () => {
      component.groupId = 'group-1';
      component.scopeKeyStatus.set('no_session');
      fixture.detectChanges();

      expect(
        fixture.nativeElement.querySelector('app-crypto-recovery-panel'),
      ).not.toBeNull();
    });

    it('owner/admin facing pending is NOT blocked from submitting', () => {
      component.groupId = 'group-1';
      asOwner();
      component.scopeKeyStatus.set('pending');

      expect(component.scopeKeyBlocked()).toBe(false);
    });

    it('banner auto-clears reactively when status flips to ready', () => {
      component.groupId = 'group-1';
      component.scopeKeyStatus.set('no_session');
      expect(component.scopeKeyBlocked()).toBe(true);

      component.scopeKeyStatus.set('ready');

      expect(component.scopeKeyBlocked()).toBe(false);
      expect(component.scopeKeyMessage()).toBe('');
    });

    it('concurrent resolutions mint the key only once (in-flight guard)', async () => {
      let resolveMint!: (k: CryptoKey) => void;
      mockGroupKeyService.resolveGroupKey.mockResolvedValue({
        status: 'pending',
      });
      mockGroupKeyService.createAndStoreGroupKey.mockReturnValue(
        new Promise<CryptoKey>((res) => {
          resolveMint = res;
        }),
      );
      validForm();
      asOwner();

      const first = component.onSubmit();
      const second = component.onSubmit();
      resolveMint(mockCryptoKey);
      await Promise.all([first, second]);

      expect(mockGroupKeyService.createAndStoreGroupKey).toHaveBeenCalledTimes(
        1,
      );
    });
  });

  // --- Household UX (contribution record, not a shared/split expense) ---
  describe('household UX', () => {
    const members = [
      {
        id: 'gm-1',
        role: 'owner',
        joinStatus: 'active',
        user: { id: 'user-1', displayName: 'Praveen', email: 'p@e.com' },
      },
      {
        id: 'gm-2',
        role: 'member',
        joinStatus: 'active',
        user: { id: 'user-2', displayName: 'Naveen', email: 'n@e.com' },
      },
    ] as any;

    function setupHousehold(
      patch: Record<string, unknown> = {
        paidByUserId: 'user-1',
        amountTotal: 1000,
        currency: 'INR',
      },
    ): HTMLElement {
      component.groupId = 'grp-1';
      component.groupCurrency = 'INR';
      component.groupType = 'household';
      component.members = members;
      component.expenseForm.patchValue(patch);
      fixture.detectChanges();
      return fixture.nativeElement as HTMLElement;
    }

    it('new household expense: hides the split editor and shows the contribution record', () => {
      const el = setupHousehold();
      expect(
        el.querySelector('[data-testid="household-contribution-amount"]'),
      ).toBeTruthy();
      expect(
        el.querySelector('[data-testid="household-contribution-help"]'),
      ).toBeTruthy();
      // No split-mode toggle / participant editor for household.
      expect(el.querySelector('[data-testid="split-mode-equal"]')).toBeNull();
      expect(el.querySelector('[data-testid="split-mode-custom"]')).toBeNull();
    });

    it('names the payer and shows the full amount as the contribution', () => {
      const el = setupHousehold();
      const help = el.querySelector(
        '[data-testid="household-contribution-help"]',
      )!.textContent!;
      expect(help).toContain('paid by');
      expect(help).toContain('Praveen');
      expect(help).toContain('not split between household members');
      const amount = el.querySelector(
        '[data-testid="household-contribution-amount"]',
      )!.textContent!;
      expect(amount).toContain('1,000'); // full amount, currency-formatted
    });

    it('edit mode: displays the existing payer and amount', () => {
      const el = setupHousehold({
        paidByUserId: 'user-2',
        amountTotal: 750,
        currency: 'INR',
      });
      expect(
        el.querySelector('[data-testid="household-contribution-help"]')!
          .textContent,
      ).toContain('Naveen');
      expect(
        el.querySelector('[data-testid="household-contribution-amount"]')!
          .textContent,
      ).toContain('750');
    });

    it('refund: helper text says "received by"', () => {
      const el = setupHousehold({
        paidByUserId: 'user-1',
        amountTotal: 1000,
        currency: 'INR',
        transactionType: 'refund',
      });
      expect(
        el.querySelector('[data-testid="household-contribution-help"]')!
          .textContent,
      ).toContain('received by');
    });

    it('normal-group regression: split editor is shown, household UI absent', () => {
      component.groupId = 'grp-1';
      component.groupCurrency = 'INR';
      component.groupType = 'normal';
      component.members = members;
      component.expenseForm.patchValue({
        paidByUserId: 'user-1',
        amountTotal: 1000,
        currency: 'INR',
      });
      fixture.detectChanges();
      const el = fixture.nativeElement as HTMLElement;
      expect(el.querySelector('[data-testid="split-mode-equal"]')).toBeTruthy();
      expect(
        el.querySelector('[data-testid="household-contribution-amount"]'),
      ).toBeNull();
    });

    it('mobile layout: household record is a single compact card, not the wide scrolling split list', () => {
      const el = setupHousehold();
      // The tall/wide participant editor (max-h-52 scroller) is never rendered
      // for household — only the compact contribution card is.
      expect(el.querySelector('.max-h-52')).toBeNull();
      expect(
        el.querySelector('[data-testid="household-contribution-amount"]'),
      ).toBeTruthy();
    });
  });

  // --- DOC-3E: additive receipt-draft pre-fill (create-mode only) -------------
  describe('DOC-3E receipt prefill', () => {
    const prefill = {
      title: 'Corner Grocery',
      amountTotal: 42.5,
      currency: 'INR',
      expenseDate: '2026-08-01',
    };

    it('seeds only non-finance fields in create mode; never refund/split', () => {
      component.expense = null; // create mode
      component.prefill = prefill;
      component.ngOnChanges({ prefill: new SimpleChange(null, component.prefill, true) });

      const v = component.expenseForm.getRawValue();
      expect(v.title).toBe('Corner Grocery');
      expect(v.amountTotal).toBe(42.5); // exact — never re-derived/altered
      expect(v.currency).toBe('INR');
      expect(v.expenseDate).toBe('2026-08-01');
      // The prefill NEVER makes it a refund or changes the split mode (payer/participant
      // defaults are the modal's own existing create-mode behaviour, not the prefill).
      expect(v.transactionType).toBe('expense');
      expect(component.splitMode).toBe('equal');
    });

    it('is IGNORED in edit mode (existing expense wins; no silent overwrite)', () => {
      component.expense = { id: 'exp-1' } as any; // edit mode (truthy)
      component.prefill = prefill;
      // Only the prefill change fires; the edit-mode branch (changes['expense']) does not.
      component.ngOnChanges({ prefill: new SimpleChange(null, component.prefill, true) });

      // Guard `!this.expense` blocks the prefill — the title stays at its default.
      expect(component.expenseForm.getRawValue().title).toBe('');
    });

    it('patches only provided fields (undefined fields leave form defaults intact)', () => {
      component.expense = null;
      component.prefill = { amountTotal: 10 };
      const originalDate = component.expenseForm.getRawValue().expenseDate;
      component.ngOnChanges({ prefill: new SimpleChange(null, component.prefill, true) });

      const v = component.expenseForm.getRawValue();
      expect(v.amountTotal).toBe(10);
      expect(v.title).toBe(''); // not provided → unchanged
      expect(v.expenseDate).toBe(originalDate); // not provided → unchanged
    });
  });
});
